################################################################################
# Rakefile 
# 
# William Madden, w.a.madden@gmail.com
# 23/04/2010
################################################################################

task :run do
  system('./flashcards ../../data/sample.index')
end

task :default => [:run]

